// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSPManagementSystem.Data;

#nullable disable

namespace OSPManagementSystem.Migrations
{
    [DbContext(typeof(OSPContext))]
    [Migration("20250602181805_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRescueAction", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("RescueActionsId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "RescueActionsId");

                    b.HasIndex("RescueActionsId");

                    b.ToTable("EquipmentRescueAction");
                });

            modelBuilder.Entity("Firefighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Firefighters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff1@osp.pl",
                            FirstName = "Imię1",
                            IsActive = true,
                            LastName = "Nazwisko1",
                            Phone = "123456781",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff2@osp.pl",
                            FirstName = "Imię2",
                            IsActive = true,
                            LastName = "Nazwisko2",
                            Phone = "123456782",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff3@osp.pl",
                            FirstName = "Imię3",
                            IsActive = true,
                            LastName = "Nazwisko3",
                            Phone = "123456783",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1990, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff4@osp.pl",
                            FirstName = "Imię4",
                            IsActive = true,
                            LastName = "Nazwisko4",
                            Phone = "123456784",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1990, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff5@osp.pl",
                            FirstName = "Imię5",
                            IsActive = true,
                            LastName = "Nazwisko5",
                            Phone = "123456785",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1990, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff6@osp.pl",
                            FirstName = "Imię6",
                            IsActive = true,
                            LastName = "Nazwisko6",
                            Phone = "123456786",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff7@osp.pl",
                            FirstName = "Imię7",
                            IsActive = true,
                            LastName = "Nazwisko7",
                            Phone = "123456787",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1990, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff8@osp.pl",
                            FirstName = "Imię8",
                            IsActive = true,
                            LastName = "Nazwisko8",
                            Phone = "123456788",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1990, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff9@osp.pl",
                            FirstName = "Imię9",
                            IsActive = true,
                            LastName = "Nazwisko9",
                            Phone = "123456789",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1990, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ff10@osp.pl",
                            FirstName = "Imię10",
                            IsActive = true,
                            LastName = "Nazwisko10",
                            Phone = "1234567810",
                            Rank = "Strażak"
                        });
                });

            modelBuilder.Entity("FirefighterRescueAction", b =>
                {
                    b.Property<int>("FirefightersId")
                        .HasColumnType("int");

                    b.Property<int>("RescueActionsId")
                        .HasColumnType("int");

                    b.HasKey("FirefightersId", "RescueActionsId");

                    b.HasIndex("RescueActionsId");

                    b.ToTable("FirefighterRescueAction");
                });

            modelBuilder.Entity("FirefighterTraining", b =>
                {
                    b.Property<int>("FirefightersId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingsId")
                        .HasColumnType("int");

                    b.HasKey("FirefightersId", "TrainingsId");

                    b.HasIndex("TrainingsId");

                    b.ToTable("FirefighterTraining");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionEquipment", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("ActionId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ActionEquipments");

                    b.HasData(
                        new
                        {
                            ActionId = 1,
                            EquipmentId = 1
                        },
                        new
                        {
                            ActionId = 2,
                            EquipmentId = 2
                        },
                        new
                        {
                            ActionId = 3,
                            EquipmentId = 3
                        },
                        new
                        {
                            ActionId = 4,
                            EquipmentId = 4
                        },
                        new
                        {
                            ActionId = 5,
                            EquipmentId = 5
                        },
                        new
                        {
                            ActionId = 6,
                            EquipmentId = 6
                        },
                        new
                        {
                            ActionId = 7,
                            EquipmentId = 7
                        },
                        new
                        {
                            ActionId = 8,
                            EquipmentId = 8
                        },
                        new
                        {
                            ActionId = 9,
                            EquipmentId = 9
                        },
                        new
                        {
                            ActionId = 10,
                            EquipmentId = 10
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionFirefighter", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("FirefighterId")
                        .HasColumnType("int");

                    b.HasKey("ActionId", "FirefighterId");

                    b.HasIndex("FirefighterId");

                    b.ToTable("ActionFirefighters");

                    b.HasData(
                        new
                        {
                            ActionId = 1,
                            FirefighterId = 1
                        },
                        new
                        {
                            ActionId = 2,
                            FirefighterId = 2
                        },
                        new
                        {
                            ActionId = 3,
                            FirefighterId = 3
                        },
                        new
                        {
                            ActionId = 4,
                            FirefighterId = 4
                        },
                        new
                        {
                            ActionId = 5,
                            FirefighterId = 5
                        },
                        new
                        {
                            ActionId = 6,
                            FirefighterId = 6
                        },
                        new
                        {
                            ActionId = 7,
                            FirefighterId = 7
                        },
                        new
                        {
                            ActionId = 8,
                            FirefighterId = 8
                        },
                        new
                        {
                            ActionId = 9,
                            FirefighterId = 9
                        },
                        new
                        {
                            ActionId = 10,
                            FirefighterId = 10
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastInspectionDate = new DateTime(2025, 5, 23, 20, 18, 4, 67, DateTimeKind.Local).AddTicks(746),
                            Name = "Sprzęt1",
                            SerialNumber = "SN001",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 2,
                            LastInspectionDate = new DateTime(2025, 5, 13, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(3971),
                            Name = "Sprzęt2",
                            SerialNumber = "SN002",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 3,
                            LastInspectionDate = new DateTime(2025, 5, 3, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(3997),
                            Name = "Sprzęt3",
                            SerialNumber = "SN003",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 4,
                            LastInspectionDate = new DateTime(2025, 4, 23, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(4001),
                            Name = "Sprzęt4",
                            SerialNumber = "SN004",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 5,
                            LastInspectionDate = new DateTime(2025, 4, 13, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(4003),
                            Name = "Sprzęt5",
                            SerialNumber = "SN005",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 6,
                            LastInspectionDate = new DateTime(2025, 4, 3, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(4005),
                            Name = "Sprzęt6",
                            SerialNumber = "SN006",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 7,
                            LastInspectionDate = new DateTime(2025, 3, 24, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(4008),
                            Name = "Sprzęt7",
                            SerialNumber = "SN007",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 8,
                            LastInspectionDate = new DateTime(2025, 3, 14, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(4010),
                            Name = "Sprzęt8",
                            SerialNumber = "SN008",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 9,
                            LastInspectionDate = new DateTime(2025, 3, 4, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(4012),
                            Name = "Sprzęt9",
                            SerialNumber = "SN009",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 10,
                            LastInspectionDate = new DateTime(2025, 2, 22, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(4014),
                            Name = "Sprzęt10",
                            SerialNumber = "SN010",
                            Status = "Sprawny"
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.RescueAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RescueActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 6, 1, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(5178),
                            Description = "Opis akcji 1",
                            Location = "Lokalizacja 1",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 5, 31, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6265),
                            Description = "Opis akcji 2",
                            Location = "Lokalizacja 2",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 30, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6278),
                            Description = "Opis akcji 3",
                            Location = "Lokalizacja 3",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 5, 29, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6281),
                            Description = "Opis akcji 4",
                            Location = "Lokalizacja 4",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 5, 28, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6283),
                            Description = "Opis akcji 5",
                            Location = "Lokalizacja 5",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 5, 27, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6300),
                            Description = "Opis akcji 6",
                            Location = "Lokalizacja 6",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 5, 26, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6303),
                            Description = "Opis akcji 7",
                            Location = "Lokalizacja 7",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 5, 25, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6305),
                            Description = "Opis akcji 8",
                            Location = "Lokalizacja 8",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 5, 24, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6309),
                            Description = "Opis akcji 9",
                            Location = "Lokalizacja 9",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 5, 23, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(6311),
                            Description = "Opis akcji 10",
                            Location = "Lokalizacja 10",
                            Type = "Pożar"
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirefighterId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirefighterId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 6, 3, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7096),
                            FirefighterId = 1,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 6, 4, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7726),
                            FirefighterId = 2,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 6, 5, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7736),
                            FirefighterId = 3,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 6, 6, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7739),
                            FirefighterId = 4,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 6, 7, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7741),
                            FirefighterId = 5,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 6, 8, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7743),
                            FirefighterId = 6,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 6, 9, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7745),
                            FirefighterId = 7,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 6, 10, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7747),
                            FirefighterId = 8,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 6, 11, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7750),
                            FirefighterId = 9,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 6, 12, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(7752),
                            FirefighterId = 10,
                            Type = "Dyżur"
                        });
                });

            modelBuilder.Entity("Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 5, 30, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8705),
                            Name = "Szkolenie 1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 5, 27, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8935),
                            Name = "Szkolenie 2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 24, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8942),
                            Name = "Szkolenie 3"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 5, 21, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8945),
                            Name = "Szkolenie 4"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 5, 18, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8947),
                            Name = "Szkolenie 5"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 5, 15, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8949),
                            Name = "Szkolenie 6"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 5, 12, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8951),
                            Name = "Szkolenie 7"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 5, 9, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8953),
                            Name = "Szkolenie 8"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 5, 6, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8955),
                            Name = "Szkolenie 9"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 5, 3, 20, 18, 4, 69, DateTimeKind.Local).AddTicks(8957),
                            Name = "Szkolenie 10"
                        });
                });

            modelBuilder.Entity("EquipmentRescueAction", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.RescueAction", null)
                        .WithMany()
                        .HasForeignKey("RescueActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirefighterRescueAction", b =>
                {
                    b.HasOne("Firefighter", null)
                        .WithMany()
                        .HasForeignKey("FirefightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.RescueAction", null)
                        .WithMany()
                        .HasForeignKey("RescueActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirefighterTraining", b =>
                {
                    b.HasOne("Firefighter", null)
                        .WithMany()
                        .HasForeignKey("FirefightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionEquipment", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionFirefighter", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Firefighter", "Firefighter")
                        .WithMany()
                        .HasForeignKey("FirefighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Schedule", b =>
                {
                    b.HasOne("Firefighter", "Firefighter")
                        .WithMany("Schedules")
                        .HasForeignKey("FirefighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("Firefighter", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
