// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSPManagementSystem.Data;

#nullable disable

namespace OSPManagementSystem.Migrations
{
    [DbContext(typeof(OSPContext))]
    [Migration("20250514171002_AddRescueAction")]
    partial class AddRescueAction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Firefighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Firefighters");
                });

            modelBuilder.Entity("FirefighterRescueAction", b =>
                {
                    b.Property<int>("FirefightersId")
                        .HasColumnType("int");

                    b.Property<int>("RescueActionsId")
                        .HasColumnType("int");

                    b.HasKey("FirefightersId", "RescueActionsId");

                    b.HasIndex("RescueActionsId");

                    b.ToTable("FirefighterRescueAction");
                });

            modelBuilder.Entity("FirefighterTraining", b =>
                {
                    b.Property<int>("FirefightersId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingsId")
                        .HasColumnType("int");

                    b.HasKey("FirefightersId", "TrainingsId");

                    b.HasIndex("TrainingsId");

                    b.ToTable("FirefighterTraining");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionEquipment", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("ActionId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ActionEquipments");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionFirefighter", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("FirefighterId")
                        .HasColumnType("int");

                    b.HasKey("ActionId", "FirefighterId");

                    b.HasIndex("FirefighterId");

                    b.ToTable("ActionFirefighters");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RescueActionId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RescueActionId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.EquipmentUsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentUsageHistories");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.RescueAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RescueActions");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirefighterId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirefighterId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("FirefighterRescueAction", b =>
                {
                    b.HasOne("Firefighter", null)
                        .WithMany()
                        .HasForeignKey("FirefightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.RescueAction", null)
                        .WithMany()
                        .HasForeignKey("RescueActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirefighterTraining", b =>
                {
                    b.HasOne("Firefighter", null)
                        .WithMany()
                        .HasForeignKey("FirefightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionEquipment", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.Equipment", "Equipment")
                        .WithMany("ActionEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionFirefighter", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Firefighter", "Firefighter")
                        .WithMany()
                        .HasForeignKey("FirefighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Equipment", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", null)
                        .WithMany("Equipment")
                        .HasForeignKey("RescueActionId");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.EquipmentUsageHistory", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.Equipment", "Equipment")
                        .WithMany("EquipmentUsageHistories")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Schedule", b =>
                {
                    b.HasOne("Firefighter", "Firefighter")
                        .WithMany()
                        .HasForeignKey("FirefighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Equipment", b =>
                {
                    b.Navigation("ActionEquipments");

                    b.Navigation("EquipmentUsageHistories");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.RescueAction", b =>
                {
                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
