// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSPManagementSystem.Data;

#nullable disable

namespace OSPManagementSystem.Migrations
{
    [DbContext(typeof(OSPContext))]
    partial class OSPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRescueAction", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("RescueActionsId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "RescueActionsId");

                    b.HasIndex("RescueActionsId");

                    b.ToTable("EquipmentRescueAction");
                });

            modelBuilder.Entity("Firefighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Firefighters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jan.kowalski@osp.pl",
                            FirstName = "Jan",
                            IsActive = true,
                            LastName = "Kowalski",
                            Phone = "123456789",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1992, 8, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.nowak@osp.pl",
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Nowak",
                            Phone = "234567890",
                            Rank = "Dowódca"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1988, 3, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "piotr.zielinski@osp.pl",
                            FirstName = "Piotr",
                            IsActive = true,
                            LastName = "Zieliński",
                            Phone = "345678901",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1995, 11, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "k.wisniewska@osp.pl",
                            FirstName = "Katarzyna",
                            IsActive = true,
                            LastName = "Wiśniewska",
                            Phone = "456789012",
                            Rank = "Ratownik"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1987, 7, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marek.wojcik@osp.pl",
                            FirstName = "Marek",
                            IsActive = true,
                            LastName = "Wójcik",
                            Phone = "567890123",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1993, 6, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "magda.kaczmarek@osp.pl",
                            FirstName = "Magdalena",
                            IsActive = true,
                            LastName = "Kaczmarek",
                            Phone = "678901234",
                            Rank = "Ratownik"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1989, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "t.mazur@osp.pl",
                            FirstName = "Tomasz",
                            IsActive = true,
                            LastName = "Mazur",
                            Phone = "789012345",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1994, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ewa.krawczyk@osp.pl",
                            FirstName = "Ewa",
                            IsActive = true,
                            LastName = "Krawczyk",
                            Phone = "890123456",
                            Rank = "Dowódca"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1986, 2, 14, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pawel.piotrowski@osp.pl",
                            FirstName = "Paweł",
                            IsActive = true,
                            LastName = "Piotrowski",
                            Phone = "901234567",
                            Rank = "Strażak"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1991, 10, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a.dabrowska@osp.pl",
                            FirstName = "Agnieszka",
                            IsActive = true,
                            LastName = "Dąbrowska",
                            Phone = "012345678",
                            Rank = "Ratownik"
                        });
                });

            modelBuilder.Entity("FirefighterRescueAction", b =>
                {
                    b.Property<int>("FirefightersId")
                        .HasColumnType("int");

                    b.Property<int>("RescueActionsId")
                        .HasColumnType("int");

                    b.HasKey("FirefightersId", "RescueActionsId");

                    b.HasIndex("RescueActionsId");

                    b.ToTable("FirefighterRescueAction");
                });

            modelBuilder.Entity("FirefighterTraining", b =>
                {
                    b.Property<int>("FirefightersId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingsId")
                        .HasColumnType("int");

                    b.HasKey("FirefightersId", "TrainingsId");

                    b.HasIndex("TrainingsId");

                    b.ToTable("FirefighterTraining");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionEquipment", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("ActionId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ActionEquipments");

                    b.HasData(
                        new
                        {
                            ActionId = 1,
                            EquipmentId = 1
                        },
                        new
                        {
                            ActionId = 2,
                            EquipmentId = 2
                        },
                        new
                        {
                            ActionId = 3,
                            EquipmentId = 3
                        },
                        new
                        {
                            ActionId = 4,
                            EquipmentId = 4
                        },
                        new
                        {
                            ActionId = 5,
                            EquipmentId = 5
                        },
                        new
                        {
                            ActionId = 6,
                            EquipmentId = 6
                        },
                        new
                        {
                            ActionId = 7,
                            EquipmentId = 7
                        },
                        new
                        {
                            ActionId = 8,
                            EquipmentId = 8
                        },
                        new
                        {
                            ActionId = 9,
                            EquipmentId = 9
                        },
                        new
                        {
                            ActionId = 10,
                            EquipmentId = 10
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionFirefighter", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("FirefighterId")
                        .HasColumnType("int");

                    b.HasKey("ActionId", "FirefighterId");

                    b.HasIndex("FirefighterId");

                    b.ToTable("ActionFirefighters");

                    b.HasData(
                        new
                        {
                            ActionId = 1,
                            FirefighterId = 1
                        },
                        new
                        {
                            ActionId = 2,
                            FirefighterId = 2
                        },
                        new
                        {
                            ActionId = 3,
                            FirefighterId = 3
                        },
                        new
                        {
                            ActionId = 4,
                            FirefighterId = 4
                        },
                        new
                        {
                            ActionId = 5,
                            FirefighterId = 5
                        },
                        new
                        {
                            ActionId = 6,
                            FirefighterId = 6
                        },
                        new
                        {
                            ActionId = 7,
                            FirefighterId = 7
                        },
                        new
                        {
                            ActionId = 8,
                            FirefighterId = 8
                        },
                        new
                        {
                            ActionId = 9,
                            FirefighterId = 9
                        },
                        new
                        {
                            ActionId = 10,
                            FirefighterId = 10
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastInspectionDate = new DateTime(2024, 5, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt1",
                            SerialNumber = "SN001",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 2,
                            LastInspectionDate = new DateTime(2024, 5, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt2",
                            SerialNumber = "SN002",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 3,
                            LastInspectionDate = new DateTime(2024, 5, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt3",
                            SerialNumber = "SN003",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 4,
                            LastInspectionDate = new DateTime(2024, 5, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt4",
                            SerialNumber = "SN004",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 5,
                            LastInspectionDate = new DateTime(2024, 5, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt5",
                            SerialNumber = "SN005",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 6,
                            LastInspectionDate = new DateTime(2024, 5, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt6",
                            SerialNumber = "SN006",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 7,
                            LastInspectionDate = new DateTime(2024, 5, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt7",
                            SerialNumber = "SN007",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 8,
                            LastInspectionDate = new DateTime(2024, 5, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt8",
                            SerialNumber = "SN008",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 9,
                            LastInspectionDate = new DateTime(2024, 5, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt9",
                            SerialNumber = "SN009",
                            Status = "Sprawny"
                        },
                        new
                        {
                            Id = 10,
                            LastInspectionDate = new DateTime(2024, 5, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprzęt10",
                            SerialNumber = "SN010",
                            Status = "Sprawny"
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.RescueAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RescueActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 1",
                            Location = "Lokalizacja 1",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 2",
                            Location = "Lokalizacja 2",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 3",
                            Location = "Lokalizacja 3",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 5, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 4",
                            Location = "Lokalizacja 4",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 5",
                            Location = "Lokalizacja 5",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 5, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 6",
                            Location = "Lokalizacja 6",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 5, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 7",
                            Location = "Lokalizacja 7",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 5, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 8",
                            Location = "Lokalizacja 8",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 5, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 9",
                            Location = "Lokalizacja 9",
                            Type = "Pożar"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 5, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Opis akcji 10",
                            Location = "Lokalizacja 10",
                            Type = "Pożar"
                        });
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirefighterId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FirefighterId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 6, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 1,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 6, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 2,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 6, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 3,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 6, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 4,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 6, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 5,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 6, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 6,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 6, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 7,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 6, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 8,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 6, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 9,
                            Type = "Dyżur"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 6, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FirefighterId = 10,
                            Type = "Dyżur"
                        });
                });

            modelBuilder.Entity("Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 3"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 5, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 4"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 5"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 5, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 6"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 5, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 7"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 5, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 8"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 5, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 9"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szkolenie 10"
                        });
                });

            modelBuilder.Entity("EquipmentRescueAction", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.RescueAction", null)
                        .WithMany()
                        .HasForeignKey("RescueActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirefighterRescueAction", b =>
                {
                    b.HasOne("Firefighter", null)
                        .WithMany()
                        .HasForeignKey("FirefightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.RescueAction", null)
                        .WithMany()
                        .HasForeignKey("RescueActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirefighterTraining", b =>
                {
                    b.HasOne("Firefighter", null)
                        .WithMany()
                        .HasForeignKey("FirefightersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionEquipment", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSPManagementSystem.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.ActionFirefighter", b =>
                {
                    b.HasOne("OSPManagementSystem.Models.RescueAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Firefighter", "Firefighter")
                        .WithMany()
                        .HasForeignKey("FirefighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("OSPManagementSystem.Models.Schedule", b =>
                {
                    b.HasOne("Firefighter", "Firefighter")
                        .WithMany("Schedules")
                        .HasForeignKey("FirefighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("Firefighter", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
